sudo: required
dist: trusty
language: java
addons:
  apt:
    packages:
      - oracle-java8-installer

env:
  global:

    - NEO4J_VERSION=3.1.3 NEO4J_HOSTNAME=127.0.0.1 NEO4J_PORT=7474 NEO4J_USERNAME=neo4j NEO4J_PASSWORD=test NEO4J_HOME=neo4j-community-$NEO4J_VERSION
before_install:
  - curl http://dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz | tar xz
install:
  - $NEO4J_HOME/bin/neo4j-admin set-initial-password test
  - $NEO4J_HOME/bin/neo4j start

before_script:
  # When Neo4j is started the first time, it requires the change of the default password
#  - curl -vX POST http://neo4j:neo4j@$NEO4J_HOSTNAME:$NEO4J_PORT/user/neo4j/password -d"password=$NEO4J_PASSWORD"
