sudo: required
dist: trusty
language: java

jdk:
  - oraclejdk8

env:
  global:
    - NEO4J_VERSION=3.1.3 NEO4J_HOSTNAME=127.0.0.1 NEO4J_PORT=7474 NEO4J_USERNAME=neo4j NEO4J_PASSWORD=test NEO4J_HOME=neo4j-community-$NEO4J_VERSION

cache:
  directories:
    - $NEO4J_HOME

before_install:
# Uncomment this if rebuilding cache
  - curl http://dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz | tar xz
install:
# Uncomment this if rebuilding cache
  - $NEO4J_HOME/bin/neo4j-admin set-initial-password test
  - $NEO4J_HOME/bin/neo4j start
